"""modify message table

Revision ID: 27d729358259
Revises: 2a2b8fbb0415
Create Date: 2023-05-04 11:03:20.389220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d729358259'
down_revision = '2a2b8fbb0415'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('sender_fullname', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('sender_username', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('sender_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'sender_image_url')
    op.drop_column('chats', 'sender_username')
    op.drop_column('chats', 'sender_fullname')
    # ### end Alembic commands ###
