"""modify message table

Revision ID: 2a2b8fbb0415
Revises: cae7928d464d
Create Date: 2023-05-04 10:43:04.169976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2b8fbb0415'
down_revision = 'cae7928d464d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'sender_image_url')
    op.drop_column('chats', 'sender_fullname')
    op.drop_column('chats', 'sender_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('sender_username', sa.VARCHAR(), nullable=True))
    op.add_column('chats', sa.Column('sender_fullname', sa.VARCHAR(), nullable=True))
    op.add_column('chats', sa.Column('sender_image_url', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
