"""new_update

Revision ID: ae678a47eda5
Revises: f9e35628aad3
Create Date: 2023-04-24 10:21:33.874357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae678a47eda5'
down_revision = 'f9e35628aad3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('rev_message_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'rev_message_id')
    # ### end Alembic commands ###
