"""modify chat table

Revision ID: cae7928d464d
Revises: ae678a47eda5
Create Date: 2023-05-04 09:21:48.040423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae7928d464d'
down_revision = 'ae678a47eda5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('chat_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'chat_id')
    # ### end Alembic commands ###
