"""update_chats_table

Revision ID: f9e35628aad3
Revises: f0212e582dc0
Create Date: 2023-04-22 10:19:49.760182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e35628aad3'
down_revision = 'f0212e582dc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perticipants')
    op.drop_table('rooms')
    op.add_column('chats', sa.Column('sender_fullname', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('reciever_fullname', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('sender_username', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('reciever_username', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('sender_image_url', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('reciever_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'reciever_image_url')
    op.drop_column('chats', 'sender_image_url')
    op.drop_column('chats', 'reciever_username')
    op.drop_column('chats', 'sender_username')
    op.drop_column('chats', 'reciever_fullname')
    op.drop_column('chats', 'sender_fullname')
    op.create_table('rooms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), server_default=sa.text("'default room'"), nullable=False),
    sa.Column('created_by', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.staff_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perticipants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), server_default=sa.text("'first_name'"), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), server_default=sa.text("'last_name'"), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date_joined', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
